require 'Items/ProceduralDistributions'

-- Black Shirt (Defensive)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.5);
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 3);
table.insert(ProceduralDistributions["list"]["ClothingStorageAllShirts"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["ClothingStorageAllShirts"].items, 4);
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, 4);
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, 1);
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad1"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["LaundryLoad1"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad2"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["LaundryLoad2"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad3"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["LaundryLoad3"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad4"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["LaundryLoad5"].items, 0.1);
table.insert(ProceduralDistributions["list"]["Locker"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["Locker"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PrisonGuardLockers"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["PrisonGuardLockers"].items, 0.05);
table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, 0.1);
table.insert(ProceduralDistributions["list"]["WardrobeWomanClassy"].items, "SBTweaks.tshirt_spacebro_black");
table.insert(ProceduralDistributions["list"]["WardrobeWomanClassy"].items, 0.5);

-- White Shirt (offensive)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.5);
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 3);
table.insert(ProceduralDistributions["list"]["ClothingStorageAllShirts"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["ClothingStorageAllShirts"].items, 4);
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, 4);
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, 1);
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, 0.1);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["LaundryLoad5"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["LaundryLoad5"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad6"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["LaundryLoad6"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad7"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["LaundryLoad7"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad8"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["LaundryLoad8"].items, 0.1);
table.insert(ProceduralDistributions["list"]["Locker"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["Locker"].items, 0.05);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, 0.5);
table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions["list"]["WardrobeManClassy"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["WardrobeManClassy"].items, 0.1);
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "SBTweaks.tshirt_spacebro_white");
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 0.5);

-- Socks (Run speed)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 1);
table.insert(ProceduralDistributions["list"]["ClothingStorageFootwear"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["ClothingStorageFootwear"].items, 3);
table.insert(ProceduralDistributions["list"]["ClothingStoresSocks"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["ClothingStoresSocks"].items, 4);
table.insert(ProceduralDistributions["list"]["ClothingStoresSport"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["ClothingStoresSport"].items, 3);
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, 0.1);
table.insert(ProceduralDistributions["list"]["GymLaundry"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["GymLaundry"].items, 1);
table.insert(ProceduralDistributions["list"]["GymLockers"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["GymLockers"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad1"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["LaundryLoad1"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad2"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["LaundryLoad2"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad7"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["LaundryLoad7"].items, 0.1);
table.insert(ProceduralDistributions["list"]["LaundryLoad8"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["LaundryLoad8"].items, 0.1);
table.insert(ProceduralDistributions["list"]["Locker"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["Locker"].items, 0.05);
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, "SBTweaks.socks_spacebro");
table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, 0.5);

-- Super Dave T-Shirt
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.01);
table.insert(ProceduralDistributions["list"]["BandMerchClothes"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["BandMerchClothes"].items, 0.1);
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["ClothingStoresShirts"].items, 0.1);
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["CrateClothesRandom"].items, 1);
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["DresserGeneric"].items, 0.01);
table.insert(ProceduralDistributions["list"]["Locker"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["Locker"].items, 0.01);
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "SBTweaks.tshirt_superdave");
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 1);

-- Super Dave Helmet
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "SBTweaks.helmet_superdave");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 1);

-- Super Dave Overalls
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "SBTweaks.overalls_superdave");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["MechanicShelfOutfit"].items, "SBTweaks.overalls_superdave");
table.insert(ProceduralDistributions["list"]["MechanicShelfOutfit"].items, 1);
